import {
  Airplane,
  Bank,
  Calendar,
  Car,
  CaretDown,
  CaretUp,
  ChartLineUp,
  CreditCard,
  CurrencyBtc,
  CurrencyDollar,
  DeviceMobile,
  GlobeHemisphereWest,
  HardDrives,
  Heartbeat,
  HourglassSimpleHigh,
  HouseLine,
  Lightning,
  Money,
  MonitorPlay,
  PawPrint,
  ShoppingBagOpen,
  Star,
  Umbrella,
} from "@phosphor-icons/react";

export const icons = {
  bank: <Bank weight="duotone" />,
  car: <Car weight="duotone" />,
  creditCard: <CreditCard weight="duotone" />,
  stream: <MonitorPlay weight="duotone" />,
  house: <HouseLine weight="duotone" />,
  health: <Heartbeat weight="duotone" />,
  mobile: <DeviceMobile weight="duotone" />,
  hardDrive: <HardDrives weight="duotone" />,
  money: <Money weight="duotone" />,
  lightning: <Lightning weight="duotone" />,
  star: <Star weight="duotone" />,
  chartLineUp: <ChartLineUp />,
  umbrella: <Umbrella weight="duotone" />,
  plane: <Airplane weight="duotone" />,
  calendar: <Calendar weight="duotone" />,
  crypto: <CurrencyBtc weight="duotone" />,
  paw: <PawPrint weight="duotone" />,
  dolar: <CurrencyDollar />,
  globe: <GlobeHemisphereWest weight="duotone" />,
  bag: <ShoppingBagOpen weight="duotone" />,
  hourglass: <HourglassSimpleHigh weight="duotone" />,
  arrowDown: <CaretDown />,
  arrowUp: <CaretUp />,
};
